# Generated by Django 3.2.4 on 2021-06-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_host',
            new_name='is_staff',
        ),
    ]
